spring.application.name=backend

#spring.data.mongodb.uri=mongodb+srv://thienitcoder2004_db_user:VzjpmwhWX0m8ae90@cluster0.chbrjez.mongodb.net/bomberserver?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.auto-index-creation=true
#
#app.jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_1234567890_ABCDEFGHIJKLMNOPQRSTUVWXYZ
#app.jwt.expiration-ms=86400000
#
## Domain frontend local và domain website public
#app.frontend.url=https://client-game-bomber.vercel.app/
#app.frontend.url-2=http://localhost:3000
#
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
#logging.level.org.mongodb.driver=INFO

server.port=8080

spring.data.mongodb.uri=mongodb+srv://thienitcoder2004_db_user:VzjpmwhWX0m8ae90@cluster0.chbrjez.mongodb.net/bomberserver?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true

app.jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_1234567890_ABCDEFGHIJKLMNOPQRSTUVWXYZ
app.jwt.expiration-ms=86400000

app.frontend.allowed-origins=http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,https://game-bomber.vercel.app/,https://*.vercel.app

# Ch? dùng local ?? test tr??c
app.frontend.url=http://localhost:3000
app.frontend.url-2=http://127.0.0.1:3000

logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
logging.level.org.mongodb.driver=INFO

# DEFAULT ADMIN ACCOUNT
app.admin.enabled=true
app.admin.email=admin@gmail.com
app.admin.password=Admin@123

# MAIL SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thiendznro2010@gmail.com
spring.mail.password=zsgn weup ljfs dife
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

app.mail.from=thiendznro2010@gmail.com
app.auth.reset-otp-expire-minutes=10
app.auth.reset-otp-resend-seconds=60