spring.application.name=backend

#spring.data.mongodb.uri=mongodb+srv://thienitcoder2004_db_user:VzjpmwhWX0m8ae90@cluster0.chbrjez.mongodb.net/bomberserver?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.auto-index-creation=true
#
#app.jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_1234567890_ABCDEFGHIJKLMNOPQRSTUVWXYZ
#app.jwt.expiration-ms=86400000
#
## Domain frontend local và domain website public
#app.frontend.url=https://client-game-bomber.vercel.app/
#app.frontend.url-2=http://localhost:3000
#
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
#logging.level.org.mongodb.driver=INFO

server.port=8080

spring.data.mongodb.uri=mongodb+srv://thienitcoder2004_db_user:VzjpmwhWX0m8ae90@cluster0.chbrjez.mongodb.net/bomberserver?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true

app.jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_1234567890_ABCDEFGHIJKLMNOPQRSTUVWXYZ
app.jwt.expiration-ms=86400000

# Ch? dùng local ?? test tr??c
app.frontend.url=http://localhost:3000
app.frontend.url-2=http://127.0.0.1:3000

logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
logging.level.org.mongodb.driver=INFO