# Bomber Server - Game Config
# BOARD / MAP
game.board.rows=13
game.board.cols=15
game.board.soft-wall-rate=0.42

# PLAYER DEFAULTS
game.player.start-lives=3
game.player.start-max-bombs=3
game.player.start-bomb-range=1
game.player.start-speed-level=1
game.player.max-inventory-size=5
game.player.max-bombs=5
game.player.max-bomb-range=5
game.player.max-speed-level=5
game.player.max-lives=5
game.player.shield-duration-ms=5000

# MATCH / ROOM
game.match.default-required-players=4
game.match.min-required-players=2
game.match.max-required-players=4
game.match.start-countdown-seconds=3
game.match.tick-rate-ms=100

# TIMING
game.timing.bomb-fuse-ms=1000
game.timing.explosion-ms=350
game.timing.invulnerable-ms=1400
game.timing.freeze-duration-ms=3000

game.timing.move-cooldown-level-1-ms=160
game.timing.move-cooldown-level-2-ms=135
game.timing.move-cooldown-level-3-ms=110
game.timing.move-cooldown-level-4-ms=90
game.timing.move-cooldown-level-5-ms=75

# DROP
game.drop.item-rate=1

# SPAWN POSITIONS
game.spawn.p1-row=1
game.spawn.p1-col=1

game.spawn.p2-row=1
game.spawn.p2-col=13

game.spawn.p3-row=11
game.spawn.p3-col=1

game.spawn.p4-row=11
game.spawn.p4-col=13

# BOT
# Bán kính phát hiện người chơi
game.bot.detect-radius=6

# Số bước tối đa khi bot BFS để dí người
game.bot.chase-search-depth=8

# Số bước tối đa khi bot BFS để tìm chỗ phá tường
game.bot.break-wall-search-depth=6

# Số bước tối đa khi bot BFS để nhặt item
game.bot.item-search-depth=5

# Số bước tối đa khi bot BFS để chạy thoát bom
game.bot.escape-search-depth=8